# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WheelyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WheelyApp
  pod 'Charts'

  target 'WheelyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WheelyAppUITests' do
    # Pods for testing
  end

end
